lojaproject/lojaapp/urls.py
from django.urls import path
from.views import *

app_name = 'lojaapp'
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("sobre/", SobreView.as_view(), name="sobre"),
    path("contato/", ContatoView.as_view(), name="contato"),
    path("todos-produtos/", TodosProdutosView.as_view(), name="Todosprodutos"),
    path("produto/<slug:slug>/", ProdutoDetalheView.as_view(), name="produtodetalhe"),
    path("addcarro-<int:pro_id>/", AddCarroView.as_view(), name="addcarro"),
    path("meu-carro/", MeuCarroView.as_view(), name="meucarro"),
    path("manipular-carro/<int:cp_id>/", ManipularCarroView.as_view(), name="manipularcarro"),
    path("limpar-carrinho/", LimparCarroView.as_view(), name="limparcarro"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("registrar/", ClienteRegistrarView.as_view(), name="clienteregistrar"),
    path("sair/", ClienteSairView.as_view(), name="clientesair"),
    path("entrar/", ClienteEntrarView.as_view(), name="clienteentrar"),
    path("perfil/", ClientePerfilView.as_view(), name="clienteperfil"),
    path("perfil/pedido-<int:pk>/", ClientePedidoDetalheView.as_view(), name="clientepedidodetalhe"),
    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-pedido/<int:pk>/", AdminPedidoDetalheView.as_view(), name="adminpedidodetalhe"),
    path("admin-todos-pedidos/", AdminPedidoListaView.as_view(), name="adminpedidolista"),
    path("admin-pedido-<int:pk>-mudar/", AdminPedidoMudarStatusView.as_view(), name="adminpedidomudar"),
    path("pesquisar/", PesquisarView.as_view(), name="pesquisar"),
    path("pagamento/", PagamentoView.as_view(), name="pagamento"),
]

lojaproject/lojaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lojaapp.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lojaproject/lojaapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome_completo = models.CharField(max_length=200)
    image = models.ImageField(upload_to="admins")
    telefone = models.CharField(max_length=20)


    def __str__(self):
        return self.user.username


class Cliente(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome_completo = models.CharField(max_length=200)
    email = models.EmailField()
    endereco = models.CharField(max_length=200, null=True, blank=True)
    data_on = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.nome_completo



class Categoria(models.Model):
    titulo = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)


    def __str__(self):
        return self.titulo
    
class Produto(models.Model):
    titulo = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="produtos")
    preco_mercado = models.PositiveIntegerField()
    venda = models.PositiveIntegerField()
    descricao = models.TextField()
    garantia = models.CharField(max_length=300, null=True, blank=True)
    return_devolucao = models.CharField(max_length=300, null=True, blank=True)
    visualizacao = models.PositiveIntegerField(default=0)
    

    def __str__(self):
        return self.titulo


class Carrinho(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.SET_NULL, null=True,blank=True)
    total = models.PositiveIntegerField(default=0)
    criado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Carrinho:" + str(self.id) 
    

class CarrinhoProduto(models.Model):
    carrinho = models.ForeignKey(Carrinho, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    avaliacao = models.PositiveIntegerField()
    quantidade = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "CarrinhoProduto:" + str(self.id) + "CarrinhoProduto:" + str(self.produto.id)
    

PEDIDO_STATUS = (
    ('Pedido Recebido', 'Pedido Recebido'),
    ('Pedido Processamento', 'Pedido Processamento'),
    ('Pedido Caminho', 'Pedido Caminho'),
    ('Pedido Completado', 'Pedido Completado'),
    ('Pedido Cancelado', 'Pedido Cancelado'),
)

METHOD = (
    ("Dinehriro na Entrega", "Dinehriro na Entrega"),
    ("Knalti", "Knalti"),
)


class Pedido_order(models.Model):
    carrinho = models.OneToOneField(Carrinho, on_delete=models.CASCADE)
    ordenando_por = models.CharField(max_length=200)
    endereco_envio = models.CharField(max_length=200)
    telefone = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    endereco_envio = models.CharField(max_length=200)
    subtotal = models.PositiveIntegerField()
    disconto = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    pedido_status = models.CharField(max_length=50, choices=PEDIDO_STATUS)
    criado_em = models.DateTimeField(auto_now_add=True)
    pagamento_method = models.CharField(max_length=20, choices=METHOD, default="Dinehriro na Entrega")
    pagamento_completo = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return "Pedido:" + str(self.id)


    

lojaproject/lojaapp/forms.py
from django import forms  
from .models import Pedido_order, Cliente
from django.contrib.auth.models import User


class Checar_PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido_order
        fields = ['ordenando_por', 'endereco_envio', 'telefone', 'email', 'pagamento_method']
        
class ClienteRegistrarForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.CharField(widget=forms.EmailInput())
    
    class Meta:
        model = Cliente
        fields = ['username', 'password', 'email', 'nome_completo', 'endereco']

    def clean_username(self):
        unome = self.cleaned_data.get('username')
        if User.objects.filter(username=unome).exists():
            raise forms.ValidationError("ESTE CLIENTE JÁ EXISTE NO BANCO DE DADOS")
        return unome
    

class ClienteEntrarForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

lojaproject/lojaapp/views.py
from django.shortcuts import render, redirect
from django.urls.base import reverse
from django.views.generic import View, TemplateView, CreateView, FormView, DetailView, ListView
from django.urls import reverse_lazy
from django.http import Http404
from django.shortcuts import get_object_or_404
from .forms import Checar_PedidoForm, ClienteRegistrarForm, ClienteEntrarForm
from .models import *
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

class LojaMixin(object):
    def dispatch(self, request, *args, **kwargs):
        carro_id = request.session.get('carro_id')
        if carro_id:
            carro_obj = Carrinho.objects.filter(id=carro_id).first()
            if carro_obj and request.user.is_authenticated and hasattr(request.user, 'cliente'):
                carro_obj.cliente = request.user.cliente
                carro_obj.save()
        return super().dispatch(request, *args, **kwargs)

class HomeView(LojaMixin, TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_produtos = Produto.objects.all().order_by("-id")
        paginator = Paginator(all_produtos,4)
        page_number = self.request.GET.get('page')
        produto_list = paginator.get_page(page_number)
        context['produto_list'] = produto_list
        return context

class TodosProdutosView(LojaMixin, TemplateView):
    template_name = "todosprodutos.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['todoscategorias'] = Categoria.objects.all()
        return context

class ProdutoDetalheView(LojaMixin, TemplateView):
    template_name = "produtodetalhe.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        url_slug = self.kwargs['slug']
        produto = Produto.objects.get(slug=url_slug)
        produto.visualizacao += 1
        produto.save()
        context['produto'] = produto
        return context

class AddCarroView(LojaMixin, TemplateView):
    template_name = "addprocarro.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        produto_id = self.kwargs['pro_id']
        produto_obj = Produto.objects.get(id=produto_id)
        carro_id = self.request.session.get('carro_id', None)
        carro_obj = Carrinho.objects.filter(id=carro_id).first() if carro_id else None

        if carro_obj:
            produto_no_carrinho = carro_obj.carrinhoproduto_set.filter(produto=produto_obj)
            if produto_no_carrinho.exists():
                carrinhoproduto = produto_no_carrinho.last()
                carrinhoproduto.quantidade += 1
                carrinhoproduto.subtotal += produto_obj.venda
                carrinhoproduto.save()
                carro_obj.total += produto_obj.venda
                carro_obj.save()
            else:
                CarrinhoProduto.objects.create(
                    carrinho=carro_obj,
                    produto=produto_obj,
                    avaliacao=produto_obj.venda,
                    quantidade=1,
                    subtotal=produto_obj.venda
                )
                carro_obj.total += produto_obj.venda
                carro_obj.save()
        else:
            carro_obj = Carrinho.objects.create(total=0)
            self.request.session['carro_id'] = carro_obj.id
            CarrinhoProduto.objects.create(
                carrinho=carro_obj,
                produto=produto_obj,
                avaliacao=produto_obj.venda,
                quantidade=1,
                subtotal=produto_obj.venda
            )
            carro_obj.total += produto_obj.venda
            carro_obj.save()

        return context

class ManipularCarroView(LojaMixin, View):
    def get(self, request, *args, **kwargs):
        cp_id = self.kwargs['cp_id']
        acao = request.GET.get('acao')
        cp_obj = CarrinhoProduto.objects.get(id=cp_id)
        carro_obj = cp_obj.carrinho

        if acao == "inc":
            cp_obj.quantidade += 1
            cp_obj.subtotal += cp_obj.avaliacao
            cp_obj.save()
            carro_obj.total += cp_obj.avaliacao
            carro_obj.save()
        elif acao == "dcr":
            cp_obj.quantidade -= 1
            cp_obj.subtotal -= cp_obj.avaliacao
            cp_obj.save()
            carro_obj.total -= cp_obj.avaliacao
            carro_obj.save()
            if cp_obj.quantidade == 0:
                cp_obj.delete()
        elif acao == "rmv":
            carro_obj.total -= cp_obj.subtotal
            carro_obj.save()
            cp_obj.delete()

        return redirect("lojaapp:meucarro")

class LimparCarroView(LojaMixin, View):
    def get(self, request, *args, **kwargs):
        carro_id = request.session.get('carro_id', None)
        if carro_id:
            carrinho = Carrinho.objects.get(id=carro_id)
            carrinho.carrinhoproduto_set.all().delete()
            carrinho.total = 0
            carrinho.save()
        return redirect("lojaapp:meucarro")

# checkout view corrigida
class CheckoutView(LojaMixin, CreateView):
    template_name = "processar.html"
    form_class = Checar_PedidoForm
    success_url = reverse_lazy("lojaapp:home")

    def dispatch(self, request, *args, **kwargs):
        if not (request.user.is_authenticated and hasattr(request.user, 'cliente')):
            return redirect("/entrar/?next=/checkout/")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        carro_id = self.request.session.get('carro_id', None)
        carrinho_obj = Carrinho.objects.filter(id=carro_id).first() if carro_id else None
        context['carrinho'] = carrinho_obj
        return context

    def form_valid(self, form):
        carrinho_id = self.request.session.get('carro_id')
        carrinho_obj = Carrinho.objects.filter(id=carrinho_id).first()
        if not carrinho_obj:
            return redirect("lojaapp:home")

        # Preenche dados do pedido
        form.instance.carrinho = carrinho_obj
        form.instance.subtotal = carrinho_obj.total
        form.instance.disconto = 0
        form.instance.total = carrinho_obj.total
        form.instance.pedido_status = "Pedido Recebido"

        # Salva o pedido
        pedido = form.save()

        # Limpa o carrinho da sessão
        if 'carro_id' in self.request.session:
            del self.request.session['carro_id']

        # Redireciona para pagamento
        pm = form.cleaned_data.get('pagamento_method')
        if pm == "Khalti":
            return redirect(reverse("lojaapp:pagamento") + "?order_id=" + str(pedido.id))
        
        return super().form_valid(form)


class PagamentoView(View):
    def get(self, request, *args, **kwargs):
        o_id = request.GET.get('order_id')
        try:
            pedido = get_object_or_404(Pedido_order, id=o_id)
        except Pedido_order.DoesNotExist:
            raise Http404("Pedido não encontrado.")
        
        context = {
            "pedido": pedido,
            "order_id": o_id,
        }
        return render(request, "pagamento.html", context)

class MeuCarroView(LojaMixin, TemplateView):
    template_name = "meucarro.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        carro_id = self.request.session.get('carro_id', None)
        carrinho = Carrinho.objects.get(id=carro_id) if carro_id else None
        context['carrinho'] = carrinho
        return context

class ClienteRegistrarView(CreateView):
    template_name = "clienteregistrar.html"
    form_class = ClienteRegistrarForm
    success_url = reverse_lazy("lojaapp:home")

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        email = form.cleaned_data.get('email')

        if User.objects.filter(username=username).exists():
            form.add_error('username', 'Este nome de usuário já está em uso.')
            return self.form_invalid(form)
        
        user = User.objects.create_user(username=username, email=email, password=password)
        form.instance.user = user

        login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        return self.request.GET.get("next", self.success_url)

class ClienteSairView(View):
    def get(self, request):
        logout(request)
        return redirect("lojaapp:home")

class ClienteEntrarView(FormView):
    template_name = "clienteentrar.html"
    form_class = ClienteEntrarForm
    success_url = reverse_lazy("lojaapp:home")

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if user is not None and Cliente.objects.filter(user=user).exists():
            login(self.request, user)
            return super().form_valid(form)
        else:
            return render(self.request, self.template_name, {
                "form": form,
                "error": "USUÁRIO E SENHA NÃO CORRESPONDEM!"
            })

    def get_success_url(self):
        return self.request.GET.get("next", self.success_url)

class SobreView(LojaMixin, TemplateView):
    template_name = "sobre.html"

class ContatoView(LojaMixin, TemplateView):
    template_name = "contato.html"

class ClientePerfilView(TemplateView):
    template_name = "clienteperfil.html"

    def dispatch(self, request, *args, **kwargs):
        if not (request.user.is_authenticated and Cliente.objects.filter(user=request.user).exists()):
            return redirect("/entrar/?next=/perfil/")

lojaproject/lojaapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <a class="navbar-brand" href="{% url 'lojaapp:home' %}">Loja Django 3.1</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'lojaapp:home' %}">HOME <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'lojaapp:Todosprodutos' %}">CATEGORIAS</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'lojaapp:meucarro' %}">CARRINHO</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        MINHA CONTA
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if request.user.cliente %}

                        <a class="dropdown-item" href="{% url 'lojaapp:clienteentrar' %}">ENTRAR</a> |
                        <a class="dropdown-item" href="{% url 'lojaapp:clienteperfil' %}">MEU PERFIL</a> |
                        <a class="dropdown-item" href="{% url 'lojaapp:clientesair' %}">SAIR</a>

                        {% else %}

                        <a class="dropdown-item" href="{% url 'lojaapp:clienteregistrar' %}">CADASTRAR CLIENTES</a> |
                        <a class="dropdown-item" href="{% url 'lojaapp:clienteentrar' %}">ENTRAR</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'lojaapp:pesquisar' %}" method="GET">
                <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Pesquisar Produtos" aria-label="Search" required>
                <button class="btn btn-warning my-2 my-sm-0" type="submit">Pesquisar</button>
            </form>
        </div>
    </nav>
    <hr>
    {% block content %}

    {% endblock content %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>
</body>

</html>

lojaproject/lojaapp/templates/clienteentrar.html
{% extends 'base.html' %}
{% block title %}ENTRAR{% endblock %}

{% block content %}
<style>
    .errorlist {
        color: red;
        list-style: none;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>ENTRAR</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn-sm btn-success">Entrar</button>
                {% if error %}

                <li style="color: red; list-style-type:none;">{{error}}</li>

                {% endif %}
            </form>
            <p>Se você ainda não é cadastrado? Cadastra-se <a href="{% url 'lojaapp:clienteregistrar' %}{% if request.GET.next%}?next={{request.GET.next}}{% endif %}"> Cadastrar</a></p>
        </div>
    </div>
</div> 

{% endblock %}

lojaproject/lojaapp/templates/clienteregistrar.html
{% extends 'base.html' %}
{% block title %}CADASTRAR CLIENTES{% endblock %}

{% block content %}
<style>
    .errorlist {
        color: red;
        list-style: none;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>CADASTRAR CLIENTES</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-primary">Cadastrar Clientes</button>
            </form>
            <p>Você já é cadastrado? <a href="{% url 'lojaapp:clienteentrar' %}"> Faça o login</a></p>
        </div>
    </div>
</div>

{% endblock %}

lojaproject/lojaapp/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center">SEJA BEM-VINDO À PÁGINA HOME</h1>
    <hr>
    <div class="row mt-3">
        {% for p in produto_list %}
        <div class="col-md-3 card">
            <div class="m-4">
                <h4><a href="{% url 'lojaapp:produtodetalhe' p.slug %}">{{ p.titulo }}</a></h4>
                <img src="{{ p.image.url }}" alt="" class="img-fluid" style="height: 200px; object-fit: contain;">
                <p class="mt-3">Preço: <strike>R$ {{ p.preco_mercado }}</strike> R$ {{ p.venda }}</p>
                <a href="{% url 'lojaapp:addcarro' p.id %}" class="btn btn-success">Comprar</a>
            </div>
        </div>
        {% endfor %}
    </div>


    <nav aria-label="Navegação de página">
        <ul class="pagination justify-content-center mt-4">

            {% if produto_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ produto_list.previous_page_number }}">Anterior</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Anterior</span>
            </li>
            {% endif %}

 
            {% for i in produto_list.paginator.page_range %}
            {% if i == produto_list.number %}
            <li class="page-item active">
                <span class="page-link">{{ i }}</span>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
            {% endif %}
            {% endfor %}

            {% if produto_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ produto_list.next_page_number }}">Próximo</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Próximo</span>
            </li>
            {% endif %}

        </ul>
    </nav>
</div>
{% endblock %}

lojaproject/lojaapp/templates/meucarro.html
{% extends 'base.html' %}
{% block title %}MEU CARRINHO{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4>ITEMS DO CARRINHO</h4>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Codigo</th>
                        <th>Produto</th>
                        <th>Avaliacao</th>
                        <th>Quantidade</th>
                        <th>Subtotal</th>
                        <th>Açao</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in carrinho.carrinhoproduto_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.produto.titulo}}</td>
                        <td>{{cp.avaliacao}}</td>
                        <td>{{cp.quantidade}}</td>
                        <td>{{cp.subtotal}}</td>
                        <td>
                            <a href="{% url 'lojaapp:manipularcarro' cp.id %}?acao=inc" class="btn btn-success"> + </a>
                            <a href="{% url 'lojaapp:manipularcarro' cp.id %}?acao=dcr" class="btn btn-warning"> - </a>
                            <a href="{% url 'lojaapp:manipularcarro' cp.id %}?acao=rmv" class="btn btn-danger"> x </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Carrinho Total:</th>
                        <th>R$ {{carrinho.total|floatformat:2}}</th>
                        {% if carrinho.carrinhoproduto_set.all %}
                        <th><a href="{% url 'lojaapp:limparcarro' %}" class="btn-sm btn-warning">Limpar Carrinho</a></th>
                        {% endif %}
                    </tr>
                    {% if carrinho.carrinhoproduto_set.all %}
                    <tr>
                        <th><a href="{% url 'lojaapp:checkout' %}" class="btn-sm btn-info">Processar Compra</a></th>
                    </tr>
                    {% endif %}  
                </tbody>
        </div>
    </div>
</div>

{% endblock %}

lojaproject/lojaapp/templates/pesquisar.html
{% extends 'base.html' %}
{% block title %}PESQUISAR PRODUTOS{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>RESULTADO DA SUA PESQUISA <span class="text-success">"{{ request.GET.keyword }}"</span></h3>
            <hr>
            {% for result in results %}
            <div class="row mb-4">
                <div class="col-md-4">
                    <img src="{{ result.image.url }}" class="img-fluid" alt="{{ result.titulo }}">
                </div>
                <div class="col-md-8">
                    <h4><a href="{% url 'lojaapp:produtodetalhe' result.slug %}">{{ result.titulo }}</a></h4>
                    <p>{{ result.descricao|truncatewords:50 }}</p>
                    <p>Politica Devolucao: {{result.return_devolucao}}</p>
                    <a href="{% url 'lojaapp:addcarro' result.id %}" class="btn btn-success">Comprar</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

lojaproject/lojaapp/templates/todosprodutos.html
{% extends 'base.html' %}
{% block title %}TODOS PRODUTOS{% endblock %}

{% block content %}
<div class="container">
    <h1>PRODUTOS POR CATEGORIA</h1>
    <hr>
    {% for cat in todoscategorias %}

    <h1>{{ cat.titulo }}</h1>

    <div class="row mt-3">
        {% for p in cat.produto_set.all %}
        <div class="col-md-4">
            <div class="m-4">
                <h4><a href="{% url 'lojaapp:produtodetalhe' p.slug %}">{{ p.titulo }}</a></h4>
                <img src="{{ p.image.url }}" alt="" class="img-fluid" style="height: 100px; object-fit: cover;">
                <p class="mt-3">Preço: <strike> R$ {{ p.preco_mercado }}</strike> R$ {{ p.venda }}</p>
                <a href="{% url 'lojaapp:addcarro' p.id %}" class="btn btn-success">Comprar</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}